# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1041917a2a083ecde84538b66bb75320f851c6cf66045c2dc2c9653ef093d2ec78634335de74dce2a781ed5fdafec3f666ac2d7666cad99bb644e809e513b8bc

test:
  secret_key_base: 9c6226cfd48ff806f3dce5bf570e8482ba60003c86236b43b0680ef0e440f2c761e7cf4ccdc6c1b18af10f0c90f0cbbe895d27cef6d92b2573c48fe467a90bbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
